In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore") 

import os
item_lst = os.listdir()

In [2]:
path = "C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/"

In [3]:
item_lst = os.listdir(path)

In [4]:
tempData =[['vechileTempName','ReviewTempTitle','Review','Rating']]

In [5]:
reviewDataSet  = pd.DataFrame()

In [6]:
reviewDataSet

Empty DataFrame
Columns: []
Index: []

In [7]:
for i in range (0,len(item_lst)):
    tempDataSet = pd.read_csv(path+item_lst[i],engine='python', error_bad_lines=False)
    print(path+item_lst[i])
    tempDataSet =  tempDataSet.drop(['Unnamed: 0','Review_Date','Author_Name'],axis=1)
    reviewDataSet = reviewDataSet.append(tempDataSet,ignore_index=True)

C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_dodge.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_ferrari.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_fiat.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_ford.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_genesis.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_hummer.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_hyundai.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_infiniti.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_isuzu.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_jaguar.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_jeep.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_kia.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_lamborghini.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_land-rover.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_lexus.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_lincoln.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_lotus.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_maserati.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_maybach.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_mazda.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_mclaren.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_mercedes-benz.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_mercury.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_mini.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_mitsubishi.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_nissan.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_pontiac.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_porsche.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_rolls-royce.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_subaru.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_suzuki.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_tesla.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scraped_Car_Review_volvo.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_Acura.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_AlfaRomeo.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_AMGeneral.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_AstonMartin.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_Audi.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_Bentley.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_BMW.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_Bugatti.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_Buick.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_Cadillac.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_Chevrolet.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_chrysler.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_GMC.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_Honda.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_Toyota.csv
C:/Users/offic/OneDrive/Documents/NationalCollegeOfIreland/GitRepo/NCI ALL Data/National-College-Of-Ireland/RIC/Project/CarReviewDatasetKaggle/Scrapped_Car_Review_Volkswagen.csv

In [8]:
reviewDataSet = reviewDataSet.dropna()
reviewDataSet = reviewDataSet.reset_index()
reviewDataSet = reviewDataSet.drop(['index'],axis=1)

In [9]:
reviewDataSet.shape

(214808, 4)

In [10]:
brands = []

for i in item_lst:
    i = i.replace('Scraped_Car_Review_', '')
    i  = i.replace('Scrapped_Car_Review_', '')
    brnd_name = i[:-4]
    brands.append(brnd_name)

In [11]:
brands

['dodge',
 'ferrari',
 'fiat',
 'ford',
 'genesis',
 'hummer',
 'hyundai',
 'infiniti',
 'isuzu',
 'jaguar',
 'jeep',
 'kia',
 'lamborghini',
 'land-rover',
 'lexus',
 'lincoln',
 'lotus',
 'maserati',
 'maybach',
 'mazda',
 'mclaren',
 'mercedes-benz',
 'mercury',
 'mini',
 'mitsubishi',
 'nissan',
 'pontiac',
 'porsche',
 'rolls-royce',
 'subaru',
 'suzuki',
 'tesla',
 'volvo',
 'Acura',
 'AlfaRomeo',
 'AMGeneral',
 'AstonMartin',
 'Audi',
 'Bentley',
 'BMW',
 'Bugatti',
 'Buick',
 'Cadillac',
 'Chevrolet',
 'chrysler',
 'GMC',
 'Honda',
 'Toyota',
 'Volkswagen']

In [12]:
tempBrandData=[]
tempdf = []

for i in range (0,len(reviewDataSet.index)):
    tempBrandData.append('temp')
reviewDataSet['Brand'] = tempBrandData

for i in range (0,len(reviewDataSet.index)):
    for j in brands:
        if j.upper() in reviewDataSet['Vehicle_Title'][i].upper():
            reviewDataSet['Brand'][i] = j
            break

In [13]:
reviewDataSet = reviewDataSet.drop(['Vehicle_Title'],axis=1)
reviewDataSet

,Review_Title,Review,Rating,Brand
0,Great delivery vehicle,It's been a great delivery vehicle for my caf...,4.625,dodge
1,Disappointmnet,Bought this car as a commuter vehicle for a v...,2.125,dodge
2,Sweet van,"This van rocks its the best, lots of \rroom. ...",5.000,dodge
3,Keven Smith,Great work vehicle. Drives nice. has lots of ...,4.500,dodge
4,Not what Dodge used to be,Good solid frame and suspension. Well equipp...,2.875,dodge
...,...,...,...,...
214803,Good Value,I have owned the Tiguan for a year and 4 mont...,4.000,Volkswagen
214804,Great Ride - But Typical VW,"Now had 2+ months with SUV. Nice SUV, handle...",3.000,Volkswagen
214805,Quality Over Quantity,Smaller dimensions and my driving experience ...,5.000,Volkswagen
214806,"Not too big, not too small",We have had our 2016 Tiguan for a month. Prio...,4.000,Volkswagen
214807,Good pick for its class,The Tiguan S can be had for a reasonable 24k ...,4.000,Volkswagen

In [14]:
reviewDataSet.isna().sum()

Review_Title    0
Review          0
Rating          0
Brand           0
dtype: int64

## Adding The Happiness Scale to the dataset based on rating 
### 0-1 > Very Sad
### 1-2 > sad
### 2-3 > Okay , Neutral Emotion
### 3-4 > Happy,
### 4-4.5 >  Very Happy
### 4.5-5 > Very Happy , Highly Satisfied

In [15]:
tempData=[]
for i in range (0,len(reviewDataSet.index)):
    tempData.append('temp')
reviewDataSet['Happiness_Level'] = tempData

for i in range (0,len(reviewDataSet.index)):
    if reviewDataSet['Rating'][i]<=1.0:
        reviewDataSet['Happiness_Level'][i]='Very Sad'
    elif reviewDataSet['Rating'][i]>1.0 and reviewDataSet['Rating'][i]<=2.0 :
        reviewDataSet['Happiness_Level'][i]='Sad'
    elif reviewDataSet['Rating'][i]>2.0 and reviewDataSet['Rating'][i]<=3.0:
        reviewDataSet['Happiness_Level'][i]='Neutral'
    elif reviewDataSet['Rating'][i]>3.0 and reviewDataSet['Rating'][i]<=4.0:
        reviewDataSet['Happiness_Level'][i]='Happy'
    elif reviewDataSet['Rating'][i]>4.0 and reviewDataSet['Rating'][i]<=4.5:
        reviewDataSet['Happiness_Level'][i]='Very Happy'
    elif reviewDataSet['Rating'][i]>4.5 and reviewDataSet['Rating'][i]<=5.0:
        reviewDataSet['Happiness_Level'][i]='Excellent'
    
reviewDataSet

,Review_Title,Review,Rating,Brand,Happiness_Level
0,Great delivery vehicle,It's been a great delivery vehicle for my caf...,4.625,dodge,Excellent
1,Disappointmnet,Bought this car as a commuter vehicle for a v...,2.125,dodge,Neutral
2,Sweet van,"This van rocks its the best, lots of \rroom. ...",5.000,dodge,Excellent
3,Keven Smith,Great work vehicle. Drives nice. has lots of ...,4.500,dodge,Very Happy
4,Not what Dodge used to be,Good solid frame and suspension. Well equipp...,2.875,dodge,Neutral
...,...,...,...,...,...
214803,Good Value,I have owned the Tiguan for a year and 4 mont...,4.000,Volkswagen,Happy
214804,Great Ride - But Typical VW,"Now had 2+ months with SUV. Nice SUV, handle...",3.000,Volkswagen,Neutral
214805,Quality Over Quantity,Smaller dimensions and my driving experience ...,5.000,Volkswagen,Excellent
214806,"Not too big, not too small",We have had our 2016 Tiguan for a month. Prio...,4.000,Volkswagen,Happy
214807,Good pick for its class,The Tiguan S can be had for a reasonable 24k ...,4.000,Volkswagen,Happy

In [16]:
reviewDataSet.to_csv('OldCleanedDataSet.csv',index=False)